app:
  build: .
  volumes:
    - ./app:/app
  env_file:
    - app/.env-production
  environment:
    - APP_ENV=production
    - APP_NAME
    - DB_URL
  ports:
    - "22:22"
    - "80:80"
    - "443:443"