elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
kibana:
  build: kibana
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  links:
    - elasticsearch
nginx:
  build: nginx
  volumes:
    - ./nginx/config/kibana-proxy.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/config/.htpasswd:/etc/nginx/.htpasswd
  ports:
    - "80:80"
  links:
    - kibana