elasticsearch:
  build: .docker/elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
kibana:
  build: .docker/kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
mysql:
  image: mysql:latest
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=dev
  ports:
    - "8306:3306"
# redis:   
  # image: redis
app:       
  hostname: ponticlaro-lep-stack-dev
  image: ponticlaro/lep-stack # LEP Stack current generation [Linux, NGINX and PHP-FPM]
  # image: ponticlaro/lap-stack # LAP Stack [Linux, Apache and PHP-FPM]
  # image: ponticlaro/lep-stack-v0 # LEP Stack v0 [Linux, NGINX and PHP-FPM]
  # build: . # For development. Also uncomment one of the dockerfiles bellow
  # dockerfile: Dockerfile-lep-stack # LEP Stack current generation [Linux, NGINX and PHP-FPM]
  # dockerfile: Dockerfile-lap-stack # LAP Stack [Linux, Apache and PHP-FPM]
  # dockerfile: Dockerfile-lep-stack-v0 # LEP Stack v0 [Linux, NGINX and PHP-FPM]
  volumes:
    - ./app:/app
    - ./.docker/filebeat/filebeat.dev.yml:/etc/filebeat/filebeat.yml
    - ./.docker/packetbeat/packetbeat.dev.yml:/etc/packetbeat/packetbeat.yml
    - ./.docker/topbeat/topbeat.dev.yml:/etc/topbeat/topbeat.yml
  env_file:
    - .env
  environment:
    - APP_ENV=development
  ports:
    - "8080:80"
    - "8443:443"
  links: 
    - mysql
    - elasticsearch
    # - redis