FROM ubuntu:16.04

MAINTAINER Cristiano Baptista "cristiano.baptista@ponticlaro.com"

# Install required packages
RUN apt-get dist-upgrade; \
    apt-get update; \
    apt-get install -y \
    openssh-server \
    supervisor \
    git \
    zsh \
    vim \
    htop \
    wget \
    curl \
    imagemagick \
    graphicsmagick \
    nodejs \
    npm \
    ruby \
    mysql-client \
    nginx-extras \
    php7.0-fpm \
    php7.0-curl \
    php7.0-gd \
    php7.0-mbstring \
    php7.0-mysql \
    php7.0-pgsql \
    php7.0-xml \
    php-imagick \
    php-memcached \
    php-redis \
    php-soap

# Symlink NodeJS
RUN ln -s "$(which nodejs)" /usr/bin/node

# Install node packages
# - Grunt CLI
RUN npm install -g \
    grunt-cli

# Add blackfire repo to sources list
RUN wget -O - https://packagecloud.io/gpg.key | apt-key add -
RUN echo "deb http://packages.blackfire.io/debian any main" | tee /etc/apt/sources.list.d/blackfire.list 

# Add elastic.co repo to sources list
RUN wget -O - https://packages.elasticsearch.org/GPG-KEY-elasticsearch | apt-key add -
RUN echo "deb http://packages.elastic.co/beats/apt stable main" | tee -a /etc/apt/sources.list.d/beats.list

# Install:
# - Elastic Filebeat: https://www.elastic.co/downloads/beats/filebeat/
# - Elastic Topbeat: https://www.elastic.co/downloads/beats/topbeat/
# - Elastic Packetbeat: https://www.elastic.co/downloads/beats/packetbeat/
RUN apt-get update; \
    apt-get install -y \
    filebeat \
    topbeat \
    packetbeat

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/bin/composer
RUN chmod +x /usr/bin/composer

# Copy placeholder code
ADD app /app

# NGINX: copy config files to container
ADD .docker/nginx/lep-stack-v2/config/nginx.conf /etc/nginx/nginx.conf
ADD .docker/nginx/lep-stack-v2/config/wordpress.conf /etc/nginx/sites-available/default

# PHP-FPM: copy config files to container
ADD .docker/php-fpm/lep-stack-v2/config/php.ini /etc/php/7.0/fpm/php.ini
ADD .docker/php-fpm/lep-stack-v2/config/php-fpm.conf /etc/php/7.0/fpm/php-fpm.conf
ADD .docker/php-fpm/lep-stack-v2/config/pool.d /etc/php/7.0/fpm/pool.d
ADD .docker/php-fpm/lep-stack-v2/config/conf.d/9999-blackfire.ini /etc/php/7.0/fpm/conf.d/9999-blackfire.ini

# Elastic Beats: copy config files to container
ADD .docker/filebeat/filebeat.yml /etc/filebeat/filebeat.yml
ADD .docker/topbeat/topbeat.yml /etc/topbeat/topbeat.yml
ADD .docker/packetbeat/packetbeat.yml /etc/packetbeat/packetbeat.yml

# Supervisord: copy config file to container
ADD .docker/supervisor/supervisord-lep-stack-v2.conf /etc/supervisor/supervisord.conf

# Custom Tools: 
# - Mysql Import
ADD .docker/custom-tools/mysql-import.sh /usr/bin/mysql-import
RUN chmod +x /usr/bin/mysql-import

# Expose container ports
EXPOSE 80 443

# Use supervisord to keep processes alive
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]