app:
  image: ponticlaro/lep-stack # Linux, NGINX and PHP-FPM
  # image: ponticlaro/lap-stack # Linux, Apache and PHP-FPM
  volumes:
    - ./app:/app
  env_file:
    - .env-production
  environment:
    - APP_ENV=production
    - APP_NAME
    - DB_URL
  ports:
    - "80:80"
    - "443:443"