mysql:
  image: mysql:latest
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=dev
  ports:
    - "8306:3306"
app:
  hostname: ponticlaro-lep-stack-dev-nodebug
  build: .
  image: ponticlaro/lep-stack # LEP Stack [Linux, NGINX and PHP-FPM]
  # image: ponticlaro/lap-stack # LAP Stack [Linux, Apache and PHP-FPM]
  # image: ponticlaro/lep-stack-v2 # LEP Stack v2 [Linux, NGINX and PHP-FPM]
  # build: . # For development. Also uncomment one of the dockerfiles bellow
  # dockerfile: Dockerfile-lep-stack # LEP Stack [Linux, NGINX and PHP-FPM]
  # dockerfile: Dockerfile-lap-stack # LAP Stack [Linux, Apache and PHP-FPM]
  # dockerfile: Dockerfile-lep-stack-v2 # LEP Stack v2 [Linux, NGINX and PHP-FPM]
  volumes:
    - ./app:/app
    - ./.docker/filebeat/filebeat.dev.yml:/etc/filebeat/filebeat.yml
    - ./.docker/packetbeat/packetbeat.dev.yml:/etc/packetbeat/packetbeat.yml
    - ./.docker/topbeat/topbeat.dev.yml:/etc/topbeat/topbeat.yml
  env_file:
    - .env
  environment:
    - APP_ENV=development
  ports:
    - "8080:80"
    - "8443:443"
  links:
    - mysql